### ISSUE TITLE
ESP8266 startup failure

### ISSUE THREAD

**Issue by LarryDysart** [DanielOgorchock/OmniThing#11]
Arduino IDE 1.8.9, ESP Board Mgr v2.5.0

Created & downloaded full sketch from web site.
Beside Network Sender/Receiver, only single ContactSensor configured (snippet):
   "Devices": [
        {
            "triggers": [
                {
                    "interval": 12000,
                    "offset": 0,
                    "command": "poll"
                }
            ],
            "subscriptions": [],
            "type": "ContactSensor",
            "name": "MyContact",
            "input": {
                "type": "DigitalInputPinArduino",
                "pin": 1,
                "invert": false,
                "pullup": false
            },
            "invert": false,
            "constantPoll": true
        }
    ]

On startup, the initial log output of loadJsonConfig truncates when it gets to this device - sometimes an odd character is at the end of string output, as if the terminating null is not present. I did add a log output of buffer in configWithProgmem before calling loadJsonConfig and it output fine.
Is there a different proven combination of IDE/Board Mgr I should try (or what other steps would you recommend to troubleshoot)?

**Comment by DanielOgorchock** [comment]
Sorry I missed this. Did you end up having any luck with solving it?

**Comment by LarryDysart** [comment]
Haven't been back to it yet, temporarily switched to ST_Anything until I had more time to experiment

**Comment by DanielOgorchock** [comment]
Closing for now. Feel free to reopen if the issue still persists.
