### ISSUE TITLE
omnithing.net not responding

### ISSUE THREAD

**Issue by ruhlmcu** [DanielOgorchock/OmniThing#20]
I may have missed this elsewhere. I am unable to connect to omnithing.net. Has that site been removed?
Thanks

**Comment by DanielOgorchock** [comment]
Hi Curt. My VPS provider cancelled the service tier I'd been using, and I didn't notice the email notice they sent. I'll need to migrate the site to another instance. Hopefully I'll have some time to get it back online within the next week or so.

**Comment by ruhlmcu** [comment]
Thx
