### ISSUE TITLE
Can't get hubitat to create child devices

### ISSUE THREAD

**Issue by ryancasler** [DanielOgorchock/OmniThing#3]
I created the parent device for an ESP8266 configuration and set everything up the way I thought it was supposed to be but nothing happens in Hubitat.

```
{
    "NetworkReceiver": {
        "type": "NetworkManagerEsp8266",
        "port": 8090,
        "ssid": "SSID",
        "password": "PWD"
    },
    "NetworkSender": {
        "type": "NetworkManagerEsp8266",
        "port": 39501,
        "ip": "192.168.1.12",
        "ssid": "SSID",
        "password": "PWD"
    },
    "CompositePeriphs": [],
    "Devices": [
        {
            "triggers": [],
            "subscriptions": [],
            "type": "SwitchLevel",
            "name": "Servo",
            "output": {
                "type": "ServoMotor",
                "pin": 12,
                "revertTime": null,
                "shutoffTime": 200,
                "initialPercent": 100,
                "noStartup": false,
                "minPulse": null,
                "maxPulse": null
            },
            "initial": 100
        }
    ]
}
```

The only thing I changes was my ssid and password.

**Comment by DanielOgorchock** [comment]
Hi Ryan,

Can you try adding a trigger to your Servo device? Choose an interval of something like 5000 milliseconds and a command of "poll". The parent device handler might just not be receiving any updates from the device, so it doesn't know to create the child.

**Comment by ryancasler** [comment]
Ah...okay.  I will give that a shot.  Shouldn't it be something more like 300,000 milliseconds though?  I don't want it bombarding the hub with updates every 5 seconds.  That seems a bit excessive.
