### ISSUE TITLE
Fail to connect to hub

### ISSUE THREAD

**Issue by gtbuzz94** [DanielOgorchock/OmniThing#4]
I am trying to run your software on a SparkFun ESP32 Thing, but ran into an issue that I can not solve.  I took the ZIP file that your site created and opened the INO file, compiled it and ran it.  It appears that everything ran, but it failed to connect to the Smarthings hub.  It says the Network Receiver connected.  I have the correct IP address, but it continues to fail when trying to connect.  Is there a specific port you have to connect too?  I have used 8090 and 39501 with no luck.  My hub is actually hard wired and does not use WiFi.  However, the WiFi does have access to the wired port so other devices do not have an issue connecting to the hub from WiFi.  Would this make a difference?

I have gone thru your instructions and added the device and configured the IP, port and MAC address in the ST app and that seemed to work.

I have configured an input and when that code is executed it tries to connect to the hub and it fails as well.  Any ideas where I might be going wrong with the configuration/setup?

**Comment by DanielOgorchock** [comment]
The port configured in the Network Sender should be 39500 for the SmartThings hub. I think 39501 is the Hubitat port. For your Network Receiver, you can choose any port you want, as long as you set the same port in the SmartThings app.

**Comment by gtbuzz94** [comment]
That solved the problem.  Thanks.  

I will be trying to implement my project in the next couple weeks and will let you know how it goes.  Thank you for developing this.
