### ISSUE TITLE
Failed install of omni-parent-hubitat.groovy

### ISSUE THREAD

**Issue by Su1c1deJack** [DanielOgorchock/OmniThing#9]
I'm a super guinea pig for this project Dan - kind of new to this... :)  I am going thru the install steps on this page:
https://github.com/DanielOgorchock/OmniThing

I set up the GitHubRepository, selected all Parent and Child DHs, and got an error: 
![error](https://user-images.githubusercontent.com/26962180/52051078-7b572280-2520-11e9-8e0f-437b5efbbe11.PNG)

All but two uploaded:
![error3](https://user-images.githubusercontent.com/26962180/52051138-a772a380-2520-11e9-97fc-01b1a1e43b01.PNG)

I selected these two to try again and then only one remained:
![error4](https://user-images.githubusercontent.com/26962180/52051189-cbce8000-2520-11e9-8eeb-db14acbd4d28.PNG)

Then I went to the GitHub repository and tried to manually create the uncreated DH and got this error upon saving the code:
Org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: script_dth_metadata_a7d2ca93_2b8b_4721_a01c_deae2a6cdcfd: 185: unable to resolve class hubitat.device.HubAction @ line 185, column 24. sendHubCommand(new hubitat.device.HubAction( ^ 1 error

I hope this is helpful!
Mark

**Comment by ogiewon** [comment]
That driver is for Hubitat users only, not SmartThings. You can safely ignore that error.

**Comment by Su1c1deJack** [comment]
My designation as a novice is now confirmed!  :D  Thanks Dan.  M

**Comment by ogiewon** [comment]
You’re welcome!
